In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
source_code = requests.get("http://www.statiz.co.kr/stat.php?mid=stat&re=0&ys=2018&ye=2018&se=0&te=&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR_ALL_ADJ&o2=TPA&de=1&lr=0&tr=&cv=&ml=2&pa=0&si=&cn=&sn=100").text
soup = BeautifulSoup(source_code)

/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))

In [3]:
dat = soup.find_all('span')

In [6]:
k = 45           # WAR = 대체 선수 대비 승리 기여
list_war = []  # 타자 WAR 100명 crawling

while  k < 3215:
    data = str(dat[k])
    war = data[50:54]
    list_war.append(war)
    k = k + 32
    
for i in range(len(list_war)): #리스트 내에 문자형을 float형으로 변환
    list_war[i] = float(list_war[i])  
    
list_war

[6.94,
 6.62,
 6.42,
 5.67,
 5.66,
 5.3,
 5.28,
 4.98,
 4.94,
 4.79,
 4.78,
 4.73,
 4.66,
 4.55,
 4.51,
 4.21,
 3.91,
 3.84,
 3.79,
 3.75,
 3.72,
 3.68,
 3.56,
 3.56,
 3.53,
 3.52,
 3.48,
 3.42,
 3.4,
 3.35,
 3.29,
 3.2,
 3.05,
 3.05,
 3.03,
 2.93,
 2.85,
 2.83,
 2.75,
 2.67,
 2.51,
 2.41,
 2.35,
 2.23,
 2.14,
 2.1,
 2.1,
 1.99,
 1.97,
 1.91,
 1.87,
 1.87,
 1.84,
 1.75,
 1.71,
 1.7,
 1.64,
 1.58,
 1.58,
 1.55,
 1.53,
 1.41,
 1.38,
 1.38,
 1.37,
 1.37,
 1.35,
 1.3,
 1.26,
 1.19,
 1.06,
 1.05,
 1.04,
 1.02,
 1.0,
 0.98,
 0.95,
 0.92,
 0.91,
 0.91,
 0.9,
 0.85,
 0.84,
 0.79,
 0.79,
 0.77,
 0.77,
 0.74,
 0.7,
 0.67,
 0.66,
 0.61,
 0.59,
 0.57,
 0.53,
 0.49,
 0.48,
 0.48,
 0.47,
 0.47]

In [7]:
print(list_war)

[6.94, 6.62, 6.42, 5.67, 5.66, 5.3, 5.28, 4.98, 4.94, 4.79, 4.78, 4.73, 4.66, 4.55, 4.51, 4.21, 3.91, 3.84, 3.79, 3.75, 3.72, 3.68, 3.56, 3.56, 3.53, 3.52, 3.48, 3.42, 3.4, 3.35, 3.29, 3.2, 3.05, 3.05, 3.03, 2.93, 2.85, 2.83, 2.75, 2.67, 2.51, 2.41, 2.35, 2.23, 2.14, 2.1, 2.1, 1.99, 1.97, 1.91, 1.87, 1.87, 1.84, 1.75, 1.71, 1.7, 1.64, 1.58, 1.58, 1.55, 1.53, 1.41, 1.38, 1.38, 1.37, 1.37, 1.35, 1.3, 1.26, 1.19, 1.06, 1.05, 1.04, 1.02, 1.0, 0.98, 0.95, 0.92, 0.91, 0.91, 0.9, 0.85, 0.84, 0.79, 0.79, 0.77, 0.77, 0.74, 0.7, 0.67, 0.66, 0.61, 0.59, 0.57, 0.53, 0.49, 0.48, 0.48, 0.47, 0.47]

In [5]:
k = 72                                  #WPA = 추가한 승리 확률
list_wpa = []                         #WPA 타자 100명 crawling

while  k < 3215:
    data = str(dat[k])
    wpa = data[50:54]
    list_wpa.append(wpa)
    k = k + 32
    
for i in range(len(list_wpa)):   #list내의 문자형을 float형으로 변환
    list_wpa[i] = float(list_wpa[i])

In [7]:
list_wpa

[5.8,
 6.44,
 3.91,
 5.45,
 5.41,
 4.35,
 5.89,
 4.06,
 5.7,
 4.23,
 3.95,
 3.44,
 3.9,
 3.55,
 4.73,
 2.1,
 4.23,
 4.34,
 1.69,
 2.9,
 4.72,
 -0.6,
 1.01,
 1.89,
 4.03,
 2.5,
 2.84,
 3.97,
 1.96,
 3.82,
 4.07,
 1.95,
 1.13,
 2.16,
 3.46,
 0.96,
 1.22,
 2.62,
 2.43,
 0.17,
 1.52,
 1.65,
 0.9,
 1.03,
 0.7,
 1.23,
 2.81,
 -0.5,
 -0.8,
 2.36,
 3.15,
 0.62,
 -0.7,
 -0.7,
 -0.0,
 0.72,
 2.9,
 1.16,
 0.39,
 1.34,
 0.32,
 2.57,
 2.63,
 0.77,
 0.05,
 0.37,
 0.16,
 1.04,
 -0.6,
 0.78,
 0.89,
 2.12,
 0.42,
 0.75,
 0.25,
 0.65,
 1.7,
 1.78,
 -0.3,
 1.51,
 1.62,
 1.63,
 -0.9,
 -1.0,
 1.73,
 -0.3,
 -0.2,
 0.31,
 -0.3,
 1.15,
 1.21,
 2.43,
 0.35,
 0.38,
 0.05,
 -0.4,
 -1.4,
 1.46,
 -0.8,
 1.53]

In [8]:
k = 69                         # Weighted on Base Average(출루율 스케일)
list_woba = []             #타자 wOBA 100명 crawling

while  k < 3215:
    data = str(dat[k])
    woba = data[50:54]
    list_woba.append(woba)
    k = k + 32
    
for i in range(len(list_woba)):   #list 내부의 문자형을 float형으로 변환
    list_woba[i] = float(list_woba[i])

In [10]:
list_woba

[0.438,
 0.478,
 0.431,
 0.421,
 0.41,
 0.409,
 0.432,
 0.407,
 0.411,
 0.424,
 0.422,
 0.396,
 0.413,
 0.385,
 0.387,
 0.397,
 0.398,
 0.415,
 0.379,
 0.391,
 0.391,
 0.368,
 0.36,
 0.366,
 0.399,
 0.385,
 0.404,
 0.371,
 0.376,
 0.376,
 0.364,
 0.347,
 0.37,
 0.37,
 0.36,
 0.363,
 0.384,
 0.329,
 0.38,
 0.356,
 0.357,
 0.377,
 0.397,
 0.365,
 0.342,
 0.339,
 0.375,
 0.355,
 0.337,
 0.406,
 0.377,
 0.347,
 0.331,
 0.338,
 0.381,
 0.337,
 0.369,
 0.346,
 0.368,
 0.382,
 0.388,
 0.355,
 0.362,
 0.353,
 0.37,
 0.324,
 0.34,
 0.365,
 0.337,
 0.341,
 0.402,
 0.445,
 0.326,
 0.447,
 0.311,
 0.328,
 0.351,
 0.335,
 0.367,
 0.354,
 0.353,
 0.31,
 0.304,
 0.32,
 0.333,
 0.305,
 0.312,
 0.34,
 0.351,
 0.314,
 0.369,
 0.319,
 0.342,
 0.512,
 0.356,
 0.302,
 0.302,
 0.351,
 0.319,
 0.364]

In [11]:
import pandas as pd

In [13]:
data = {'WAR':list_war, 'WPA':list_wpa, 'wOBA':list_woba}
df = pd.DataFrame(data)
df

     WAR   WPA   wOBA
0   6.94  5.80  0.438
1   6.62  6.44  0.478
2   6.42  3.91  0.431
3   5.67  5.45  0.421
4   5.66  5.41  0.410
5   5.30  4.35  0.409
6   5.28  5.89  0.432
7   4.98  4.06  0.407
8   4.94  5.70  0.411
9   4.79  4.23  0.424
10  4.78  3.95  0.422
11  4.73  3.44  0.396
12  4.66  3.90  0.413
13  4.55  3.55  0.385
14  4.51  4.73  0.387
15  4.21  2.10  0.397
16  3.91  4.23  0.398
17  3.84  4.34  0.415
18  3.79  1.69  0.379
19  3.75  2.90  0.391
20  3.72  4.72  0.391
21  3.68 -0.60  0.368
22  3.56  1.01  0.360
23  3.56  1.89  0.366
24  3.53  4.03  0.399
25  3.52  2.50  0.385
26  3.48  2.84  0.404
27  3.42  3.97  0.371
28  3.40  1.96  0.376
29  3.35  3.82  0.376
..   ...   ...    ...
70  1.06  0.89  0.402
71  1.05  2.12  0.445
72  1.04  0.42  0.326
73  1.02  0.75  0.447
74  1.00  0.25  0.311
75  0.98  0.65  0.328
76  0.95  1.70  0.351
77  0.92  1.78  0.335
78  0.91 -0.30  0.367
79  0.91  1.51  0.354
80  0.90  1.62  0.353
81  0.85  1.63  0.310
82  0.84 -0.90  0.304
83  0.79 -1.00  0.320
84  0.79  1.73  0.333
85  0.77 -0.30  0.305
86  0.77 -0.20  0.312
87  0.74  0.31  0.340
88  0.70 -0.30  0.351
89  0.67  1.15  0.314
90  0.66  1.21  0.369
91  0.61  2.43  0.319
92  0.59  0.35  0.342
93  0.57  0.38  0.512
94  0.53  0.05  0.356
95  0.49 -0.40  0.302
96  0.48 -1.40  0.302
97  0.48  1.46  0.351
98  0.47 -0.80  0.319
99  0.47  1.53  0.364

[100 rows x 3 columns]